name: KL
version: 0.1.0.0
synopsis: My Haskell project
description: See KL.pdf
maintainer: My Name <my.email@example.com>
category: Logic

ghc-options: -Wall

dependencies:
  - QuickCheck
  - base
  - containers
  - directory
  - lens
  - mtl
  - parsec
  - random
  - template-haskell

library:
  source-dirs: lib

executables:
  myprogram:
    main: Main.lhs
    source-dirs: exec
    dependencies:
      - KL

tests:
  KL:
    main: KL.lhs
    source-dirs: test
    dependencies:
      - KL
      - base
      - hspec
      - QuickCheck